---
name: test
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Erlang/OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['20', '21', '22', '23', '24']
        rebar3: ['3.14.2', '3.14.3', '3.14.4', '3.15.0', '3.15.1']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - name: Style review
        run: rebar3 lint
      - name: Cross reference analysis
        run: rebar3 as test xref
      - name: Static analysis
        run: rebar3 dialyzer
      - name: Common Tests
        run: rebar3 ct
      - name: Property tests
        run: rebar3 proper
      - name: Code coverage
        run: rebar3 as test do cover,covertool generate
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          files: _build/test/covertool/verl.covertool.xml
          name: ${{matrix.otp_vsn}}
