---
name: test
on: push
jobs:
  test:
    name: Erlang/OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['20.3.8.9', '21.3.8.9', '22.3.4.9', '23.3.1']
        rebar3: ['3.14.1', '3.14.2', '3.14.3']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1.7.0
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - name: Style review
        run: rebar3 lint
      - name: Cross reference analysis
        run: rebar3 as test xref
      - name: Static analysis
        run: rebar3 dialyzer
      - name: Common Tests
        run: rebar3 ct
      - name: Property tests
        run: rebar3 proper
      - name: Code coverage
        run: rebar3 as test do cover,covertool generate
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          files: _build/test/covertool/verl.covertool.xml
          name: ${{matrix.otp_vsn}}
